### ISSUE TITLE
Update readme for code pattern

### ISSUE THREAD

**Issue by kmh4321** [jacob-hougaard/MAX-fast-style-transfer-web-interface#1]
Hello Jacob, 
The demo looks really good!
Can you update the readme to something similar to this: https://github.com/IBM/MAX-Object-Detector-Web-App
That way it's aligned with the other code patterns we have!

**Comment by jacob-hougaard** [comment]
Hi Karthik!
Thank you :) 
I have updated the readme to align with the one you sent. Please let me know if there needs to be any changes.
